apiVersion: apps.hooli.com/v1alpha1
kind: Webservice
metadata:
  name: invoice
spec:
  image: "k8s.gcr.io/hpa-example"
  port: 80
  - app: "fullfillment"
  - app: "finance"
  healthcheck:
    path: /
  resources:
    min:
      cpu: 400m
    max:
      cpu: 800m
